### ISSUE TITLE
Convert basic SQL table dump into Laravel code

### ISSUE THREAD

**Issue by paigejulianne** [genderdirectory/genderdirectory#4]
Take a basic SQL dump (table structure only) and put it into Laravel's code.  In the end, I should be able to run 'artisan db:migrate' and it create or update the database tables.

SQL database dumps are at https://github.com/genderdirectory/sql-dumps

**Comment by gilbertozioma** [comment]
I worked on this.

**Comment by paigejulianne** [comment]
> I worked on this.

I think this is done!  Thank you!
